---
- name: 'Encryption | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Encryption | converge | apply r_pufky.srv.maria'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.maria'
