---
# yamllint disable rule:line-length
#
# Generate test encryption keys with:
#   echo -n "1;`openssl rand -hex 32`" > keyfile
#   openssl rand -hex 128 > keyfile.key
#   openssl enc -aes-256-cbc -md sha1 \
#     -pass file:keyfile.key \
#     -in keyfile \
#     -out keyfile.enc
#
# Confirm:
# * Encryption enabled and service is active and running.
#
# Reference:
# * https://mariadb.com/kb/en/file-key-management-encryption-plugin/
dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        maria_service_password: 'test'
        maria_encryption_enable: true
        maria_encryption_path: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/files/encryption'
        maria_encryption_settings:
          - 'aria-encrypt-tables'
          - 'encrypt-binlog'
          - 'encrypt-tmp-disk-tables'
          - 'encrypt-tmp-files'
          - 'loose-innodb-encrypt-log'
          - 'loose-innodb-encrypt-tables'
        maria_server_mariadb:
          - version: 'all'
            config:
              pid_file: '/run/mysqld/mysqld.pid'
              basedir: '/usr'
              bind_address: '127.0.0.1'
              expire_logs_days: 10
              file_key_management_filename: '/etc/mysql/mariadb.conf.d/encryption/keyfile.enc'
              file_key_management_filekey: 'FILE:/etc/mysql/mariadb.conf.d/encryption/keyfile.key'
              file_key_management_encryption_algorithm: 'AES_CTR'
platforms:
  - name: 'maria-debian-12-encryption'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    # - 'idempotence'  # systemd services.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
