---
- name: 'Encryption | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Encryption | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Encryption | verify | assert mariadb.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"mariadb.service" in ansible_facts.services'
          - 'ansible_facts["services"]["mariadb.service"]["state"] == "running"'  # yamllint disable-line rule:line-length
        fail_msg: '✘ mariadb.service should be enabled and running.'

    - name: 'Data directories | verify | /etc/mysql/mariadb.cnf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Data directories | verify | /etc/mysql/mariadb.cnf'
        test_src: 'files/mariadb.cnf'
        test_file: '/etc/mysql/mariadb.cnf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'

    - name:
        'Data directories | verify | /etc/mysql/mariadb.conf.d/50-server.cnf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          'Data directories | verify | /etc/mysql/mariadb.conf.d/50-server.cnf'
        test_src: 'files/50-server.cnf'
        test_file: '/etc/mysql/mariadb.conf.d/50-server.cnf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
