---
- name: 'Encryption | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Encryption | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Encryption | verify | assert mariadb.service active'
      ansible.builtin.assert:
        that:
          - '"mariadb.service" in ansible_facts.services'
          - 'ansible_facts["services"]["mariadb.service"]["state"] == "running"'
        fail_msg: 'mariadb.service should be enabled and running.'

    - name: 'Encryption | verify | query mariadb.cnf'
      ansible.builtin.copy:
        src: 'files/mariadb.cnf'
        dest: '/etc/mysql/mariadb.cnf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_maria_mariadb

    - name: 'Encryption | verify | assert mariadb.cnf'
      ansible.builtin.assert:
        that:
          - not _test_maria_mariadb.changed
        fail_msg: >
          /etc/mysql/mariadb.cnf is not in expected format:
          {{ _test_maria_mariadb.diff }}.

    - name: 'Encryption | verify | query 50-server.cnf'
      ansible.builtin.copy:
        src: 'files/50-server.cnf'
        dest: '/etc/mysql/mariadb.conf.d/50-server.cnf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_maria_50_server

    - name: 'Encryption | verify | assert 50-server.cnf'
      ansible.builtin.assert:
        that:
          - not _test_maria_50_server.changed
        fail_msg: >
          /etc/mysql/mariadb.conf.d/50-server.cnf is not in expected format:
          {{ _test_maria_50_server.diff }}.
