---
# yamllint disable rule:line-length
###############################################################################
# Annotate User Configuration
###############################################################################
# Sanitize (standardize with default values if not set) MariaDB configuration.
#
# Determine all user data directories and create/set permissions if they do not
# exist. Run run data directories as the maria user as restricted mount points
# may only allow that user to write to them (and squash everyone else to
# nobody/nogroup).
#
# A necessary evil given the limitations of argument_spec:
# * Strong validation and sanitization of user input.
# * Annotated variable providing context and rendering hints.
# * Logic updates centrally located in tasks.
# * Simplified role updates for variable changes.
# * All data touched by user is in a standard, expected format.
#
# Annotated Defaults (2.0):
# _{VAR}: dict - Annotated and sanitized default variable.
#   section: str - Section name.
#   key: str - Config file key.
#   raw: any - Raw value from user, defaults, or role defaults.
#   data: any - Processed raw value for use in rendering. Optional.
#   default: any - Role default (testing for changed defaults).
#   hint: str - Value rendering type hint (docstring types).
#   role_*: any - Role specific usage. Optional.
#   added: str - Release version variable added.
#       Special Case:
#         0.0.0: Unknown or since role inception.
#   sensitive: bool - True for PII/SPII data that should not be logged.
#   deprecated: bool - True if no longer used in current role release.
#   order: int - Order item should appear in templated files.
#
# Generates:
#   _maria: dict - Role runtime specific config.
#   _maria_map: list of dict - Annotated config map.
#   _maria_order: list of str - Config section order.
#
# Reference:
# * https://mariadb.com/docs/server/reference/full-list-of-mariadb-options-system-and-status-variables
# yamllint enable rule:line-length

- name: 'Annotate | sanitize & annotate service defaults'
  ansible.builtin.set_fact:
    _maria_srv_version: {
      section: '',
      key: '',
      raw: '{{ maria_srv_version }}',
      default: '11.rolling',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }
    _maria_srv_certs_path: {
      section: '',
      key: '',
      raw: '{{ maria_srv_certs_path }}',
      role_src: "{{ maria_srv_certs_path | regex_replace('\\/$', '') ~ '/' }}",
      role_dest: '{{ maria_role_confd ~ "/certs/" }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 2,
    }
    _maria_srv_password: {
      section: '',
      key: '',
      raw: '{{ maria_srv_password }}',
      default: '{{
          lookup("ansible.builtin.password",
                 "/dev/null",
                 chars=["ascii_lowercase", "ascii_uppercase", "digits"],
                 length=32,
                 seed=inventory_hostname)
        }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: true,
      deprecated: false,
      order: 3,
    }
    _maria_srv_purge_enable: {
      section: '',
      key: '',
      raw: '{{ maria_srv_purge_enable }}',
      default: false,
      role_value: '{{ maria_srv_purge_enable | lower }}',
      role_question: 'mariadb-server/postrm_remove_databases',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 4,
    }
    _maria_srv_user: {
      section: '',
      key: '',
      raw: '{{ maria_srv_user }}',
      default: 'mysql',
      role_uid: '',  # (str) UID.
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 5,
    }
    _maria_srv_group: {
      section: '',
      key: '',
      raw: '{{ maria_srv_group }}',
      default: 'mysql',
      role_gid: '',  # (str) GID.
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 6,
    }
    _maria_srv_create_user: {
      section: '',
      key: '',
      raw: '{{ maria_srv_create_user }}',
      default: true,
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 7,
    }
    _maria_srv_user_data_manage_enable: {
      section: '',
      key: '',
      raw: '{{ maria_srv_user_data_manage_enable }}',
      default: false,
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 8,
    }

- name: 'Annotate | sanitize & annotate config defaults'
  ansible.builtin.set_fact:
    _maria_cfg_client_all: {
      section: '50-client.cnf',
      key: 'maria_cfg_client_all',
      raw: '{{ maria_cfg_client_all }}',
      default: {},
      role_dest: '{{ maria_role_confd ~ "/50-client.cnf" }}',
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }
    _maria_cfg_client_only: {
      section: '50-client.cnf',
      key: 'maria_cfg_client_only',
      raw: '{{ maria_cfg_client_only }}',
      default: {},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 2,
    }
    _maria_cfg_encryption_enable: {
      section: 'encryption',
      key: 'maria_cfg_encryption_enable',
      raw: '{{ maria_cfg_encryption_enable }}',
      default: false,
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }
    _maria_cfg_encryption_path: {
      section: 'encryption',
      key: 'maria_cfg_encryption_path',
      raw: '{{ maria_cfg_encryption_path }}',
      role_src:
        "{{ maria_cfg_encryption_path | regex_replace('\\/$', '') ~ '/' }}",
      role_dest: '{{ maria_role_confd ~ "/encryption/" }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 2,
    }
    _maria_cfg_encryption_settings: {
      section: 'encryption',
      key: 'maria_cfg_encryption_settings',
      raw: '{{ maria_cfg_encryption_settings }}',
      default: [],
      hint: 'list of str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 3,
    }
    _maria_cfg_galera_config: {
      section: '60-galera.cnf',
      key: 'maria_cfg_galera_config',
      raw: '{{ maria_cfg_galera_config }}',
      default: {},
      role_dest: '{{ maria_role_confd ~ "/60-galera.cnf" }}',
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }
    _maria_cfg_extensions: {
      section: '90-extensions.cnf',
      key: 'maria_cfg_extensions',
      raw: '{{ maria_cfg_extensions }}',
      default: [],
      role_dest: '{{ maria_role_confd ~ "/90-extensions.cnf" }}',
      hint: 'list of dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }
    _maria_cfg_mariadb_client: {
      section: '50-mariadb-clients.cnf',
      key: 'maria_cfg_mariadb_client',
      raw: '{{ maria_cfg_mariadb_client }}',
      default: {},
      role_dest: '{{ maria_role_confd ~ "/50-mariadb-clients.cnf" }}',
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }
    _maria_cfg_mariadb_upgrade: {
      section: '50-mariadb-clients.cnf',
      key: 'maria_cfg_mariadb_upgrade',
      raw: '{{ maria_cfg_mariadb_upgrade }}',
      default: {},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 2,
    }
    _maria_cfg_mariadb_admin: {
      section: '50-mariadb-clients.cnf',
      key: 'maria_cfg_mariadb_admin',
      raw: '{{ maria_cfg_mariadb_admin }}',
      default: {},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 3,
    }
    _maria_cfg_mariadb_binlog: {
      section: '50-mariadb-clients.cnf',
      key: 'maria_cfg_mariadb_binlog',
      raw: '{{ maria_cfg_mariadb_binlog }}',
      default: {},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 4,
    }
    _maria_cfg_mariadb_check: {
      section: '50-mariadb-clients.cnf',
      key: 'maria_cfg_mariadb_check',
      raw: '{{ maria_cfg_mariadb_check }}',
      default: {},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 5,
    }
    _maria_cfg_mariadb_dump: {
      section: '50-mariadb-clients.cnf',
      key: 'maria_cfg_mariadb_dump',
      raw: '{{ maria_cfg_mariadb_dump }}',
      default: {},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 6,
    }
    _maria_cfg_mariadb_import: {
      section: '50-mariadb-clients.cnf',
      key: 'maria_cfg_mariadb_import',
      raw: '{{ maria_cfg_mariadb_import }}',
      default: {},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 7,
    }
    _maria_cfg_mariadb_show: {
      section: '50-mariadb-clients.cnf',
      key: 'maria_cfg_mariadb_show',
      raw: '{{ maria_cfg_mariadb_show }}',
      default: {},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 8,
    }
    _maria_cfg_mariadb_slap: {
      section: '50-mariadb-clients.cnf',
      key: 'maria_cfg_mariadb_slap',
      raw: '{{ maria_cfg_mariadb_slap }}',
      default: {},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 9,
    }
    _maria_cfg_mariadb_client_server: {
      section: '50-mariadb.cnf',
      key: 'maria_cfg_mariadb_client_server',
      raw: '{{ maria_cfg_mariadb_client_server }}',
      default: {'socket': '/run/mysqld/mysqld.sock'},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }
    _maria_cfg_mariadb_include_confd_enable: {
      section: '50-mariadb.cnf',
      key: 'maria_cfg_mariadb_include_confd_enable',
      raw: '{{ maria_cfg_mariadb_include_confd_enable }}',
      default: true,
      role_include: '!includedir /etc/mysql/conf.d/',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 2,
    }
    _maria_cfg_mariadb_include_mariadb_confd_enable: {
      section: '50-mariadb.cnf',
      key: 'maria_cfg_mariadb_include_mariadb_confd_enable',
      raw: '{{ maria_cfg_mariadb_include_mariadb_confd_enable }}',
      default: true,
      role_include: '{{ "!includedir " ~ maria_role_confd ~ "/" }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 3,
    }
    _maria_cfg_server_server: {
      section: '50-server.cnf',
      key: 'maria_cfg_server_server',
      raw: '{{ maria_cfg_server_server }}',
      default: {},
      role_dest: '{{ maria_role_confd ~ "/50-server.cnf" }}',
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }
    _maria_cfg_server_mariadb: {
      section: '50-server.cnf',
      key: 'maria_cfg_server_mariadb',
      raw: '{{ maria_cfg_server_mariadb }}',
      default: [{'version': 'all',
                 'config': {
                   'pid_file': '/run/mysqld/mysqld.pid',
                   'basedir': '/usr',
                   'bind_address': '127.0.0.1',
                   'expire_logs_days': 10,
                 }}],
      role_versioned_configs: [],
      hint: 'list of dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 2,
    }
    _maria_cfg_server_embedded: {
      section: '50-server.cnf',
      key: 'maria_cfg_server_embedded',
      raw: '{{ maria_cfg_server_embedded }}',
      default: {},
      hint: 'dict',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 3,
    }
    _maria_cfg_databases: {
      section: 'databases',
      key: '',
      raw: '{{ maria_cfg_databases }}',
      default: [],
      hint: 'list of dict',
      added: '0.0.0',
      sensitive: true,
      deprecated: false,
      order: 9,
    }
    _maria_cfg_databases_backup_enable: {
      section: 'databases',
      key: '',
      raw: '{{ maria_cfg_databases_backup_enable }}',
      default: true,
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 10,
    }
    _maria_cfg_databases_backup_all_enable: {
      section: 'databases',
      key: '',
      raw: '{{ maria_cfg_databases_backup_all_enable }}',
      default: true,
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 11,
    }
    _maria_cfg_databases_backup_individual_enable: {
      section: 'databases',
      key: '',
      raw: '{{ maria_cfg_databases_backup_individual_enable }}',
      default: true,
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 12,
    }
    _maria_cfg_databases_backup_dir: {
      section: 'databases',
      key: '',
      raw: "{{ maria_cfg_databases_backup_dir | regex_replace('\\/$', '') }}",
      default: '/var/lib/maria_backup',
      role_dest: '{{ maria_role_confd ~ "/maria_backup" }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 13,
    }
    _maria_cfg_databases_backup_owner: {
      section: 'databases',
      key: '',
      raw: '{{ maria_cfg_databases_backup_owner }}',
      default: 'root',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 14,
    }
    _maria_cfg_databases_backup_group: {
      section: 'databases',
      key: '',
      raw: '{{ maria_cfg_databases_backup_group }}',
      default: 'root',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 15,
    }
    _maria_cfg_databases_backup_schedule: {
      section: 'databases',
      key: '',
      raw: '{{ maria_cfg_databases_backup_schedule }}',
      default: 'weekly',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 16,
    }
    _maria_cfg_databases_backup_options: {
      section: 'databases',
      key: '',
      raw: '{{ maria_cfg_databases_backup_options }}',
      default: ["--routines", "--events", "--triggers", "--complete-insert",
                "--create-options", "--single-transaction"],
      role_options: '{{ maria_cfg_databases_backup_options | join(" ") }}',
      hint: 'list of str',
      added: '0.0.0',
      sensitive: true,
      deprecated: false,
      order: 9,
    }
    _maria_cfg_users: {
      section: 'users',
      key: '',
      raw: '{{ maria_cfg_users }}',
      default: [],
      hint: 'list of dict',
      added: '0.0.0',
      sensitive: true,
      deprecated: false,
      order: 1,
    }

- name: 'Annotate | generate version specific configs'
  ansible.builtin.set_fact:
    _maria_cfg_server_mariadb: '{{
        _maria_cfg_server_mariadb |
        combine({"role_versioned_configs":
                 _maria_cfg_server_mariadb.role_versioned_configs |
                 default([]) + [item.config | default({})]})
      }}'
  loop: '{{ _maria_cfg_server_mariadb.raw }}'
  loop_control:
    label: '{{ item.version }}'

- name: 'Annotate | generate config sections'
  ansible.builtin.set_fact:
    _maria:
      dbs: '{{
          ([_maria_cfg_mariadb_client_server.raw.datadir | default("")] +
           [_maria_cfg_server_server.raw.datadir | default("")] +
            _maria_cfg_server_mariadb.role_versioned_configs +
           [_maria_server_embedded.raw.datadir | default("")]) |
               flatten | unique | reject("equalto", "")
        }}'
