---
# yamllint disable rule:line-length
###############################################################################
# Annotate User Configuration
###############################################################################
# Sanitize (standardize with default values if not set) MariaDB configuration.
#
# Determine all user data directories and create/set permissions if they do not
# exist. Run run data directories as the maria user as restricted mount points
# may only allow that user to write to them (and squash everyone else to
# nobody/nogroup).
#
# Use r_pufky.data.v3 data annotations to enforce consistency and validation
# checks.
#
# Generates:
#   _maria: dict - Role runtime specific config.
#   _maria_map: list of dict - Annotated config map.
#   _maria_order: list of str - Config section order.
#
# Reference:
# * https://mariadb.com/docs/server/reference/full-list-of-mariadb-options-system-and-status-variables
# yamllint enable rule:line-length

- name: 'Annotate | sanitize & annotate service defaults'
  ansible.builtin.set_fact:  # noqa jinja[spacing] readability.
    _maria_srv_version: "{{ {} | r_pufky.data.v3(
        raw=maria_srv_version,
        default='11.rolling',
        hint='str',
        order=1
        )
      }}"
    _maria_srv_certs_path: "{{ {} | r_pufky.data.v3(
        raw=maria_srv_certs_path,
        _src=maria_srv_certs_path | regex_replace('\\/$', '') ~ '/',
        _dest=maria_role_confd ~ '/certs/',
        hint='str',
        order=2
        )
      }}"
    _maria_srv_password: "{{ {} | r_pufky.data.v3(
        raw=maria_srv_password,
        default=(
          lookup('ansible.builtin.password',
                 '/dev/null',
                 chars=['ascii_lowercase', 'ascii_uppercase', 'digits'],
                 length=32,
                 seed=inventory_hostname)
        ),
        hint='str',
        sensitive=true,
        order=3
        )
      }}"
    _maria_srv_purge_enable: "{{ {} | r_pufky.data.v3(
        raw=maria_srv_purge_enable,
        default=false,
        _value=maria_srv_purge_enable | lower,
        _question='mariadb-server/postrm_remove_databases',
        hint='bool',
        order=4
        )
      }}"
    _maria_srv_user: "{{ {} | r_pufky.data.v3(
        raw=maria_srv_user,
        default='mysql',
        _uid='',
        hint='str',
        order=5
        )
      }}"
    _maria_srv_group: "{{ {} | r_pufky.data.v3(
        raw=maria_srv_group,
        default='mysql',
        _gid='',
        hint='bool',
        order=6
        )
      }}"
    _maria_srv_create_user: "{{ {} | r_pufky.data.v3(
        raw=maria_srv_create_user,
        default=true,
        hint='bool',
        order=7
        )
      }}"
    _maria_srv_user_data_manage_enable: "{{ {} | r_pufky.data.v3(
        raw=maria_srv_user_data_manage_enable,
        default=false,
        hint='bool',
        order=8
        )
      }}"

- name: 'Annotate | sanitize & annotate config defaults'
  ansible.builtin.set_fact:  # noqa jinja[spacing] readability.
    _maria_cfg_client_all: "{{ {} | r_pufky.data.v3(
        section='50-client.cnf',
        key='maria_cfg_client_all',
        raw=maria_cfg_client_all,
        default={},
        _dest=maria_role_confd ~ '/50-client.cnf',
        hint='dict',
        order=1
        )
      }}"
    _maria_cfg_client_only: "{{ {} | r_pufky.data.v3(
        section='50-client.cnf',
        key='maria_cfg_client_only',
        raw=maria_cfg_client_only,
        default={},
        hint='dict',
        order=2
        )
      }}"
    _maria_cfg_encryption_enable: "{{ {} | r_pufky.data.v3(
        section='encryption',
        key='maria_cfg_encryption_enable',
        raw=maria_cfg_encryption_enable,
        default=false,
        hint='bool',
        order=1
        )
      }}"
    _maria_cfg_encryption_path: "{{ {} | r_pufky.data.v3(
        section='encryption',
        key='maria_cfg_encryption_path',
        raw=maria_cfg_encryption_path,
        _src=maria_cfg_encryption_path | regex_replace('\\/$', '') ~ '/',
        _dest=maria_role_confd ~ '/encryption/',
        hint='str',
        order=2
        )
      }}"
    _maria_cfg_encryption_settings: "{{ {} | r_pufky.data.v3(
        section='encryption',
        key='maria_cfg_encryption_settings',
        raw=maria_cfg_encryption_settings,
        default=[],
        hint='list of str',
        order=3
        )
      }}"
    _maria_cfg_galera_config: "{{ {} | r_pufky.data.v3(
        section='60-galera.cnf',
        key='maria_cfg_galera_config',
        raw=maria_cfg_galera_config,
        default={},
        _dest=maria_role_confd ~ '/60-galera.cnf',
        hint='dict',
        order=1
        )
      }}"
    _maria_cfg_extensions: "{{ {} | r_pufky.data.v3(
        section='90-extensions.cnf',
        key='maria_cfg_extensions',
        raw=maria_cfg_extensions,
        default=[],
        _dest=maria_role_confd ~ '/90-extensions.cnf',
        hint='list of dict',
        order=1
        )
      }}"
    _maria_cfg_mariadb_client: "{{ {} | r_pufky.data.v3(
        section='50-mariadb-clients.cnf',
        key='maria_cfg_mariadb_client',
        raw=maria_cfg_mariadb_client,
        default={},
        _dest=maria_role_confd ~ '/50-mariadb-clients.cnf',
        hint='dict',
        order=1
        )
      }}"
    _maria_cfg_mariadb_upgrade: "{{ {} | r_pufky.data.v3(
        section='50-mariadb-clients.cnf',
        key='maria_cfg_mariadb_upgrade',
        raw=maria_cfg_mariadb_upgrade,
        default={},
        hint='dict',
        order=2
        )
      }}"
    _maria_cfg_mariadb_admin: "{{ {} | r_pufky.data.v3(
        section='50-mariadb-clients.cnf',
        key='maria_cfg_mariadb_admin',
        raw=maria_cfg_mariadb_admin,
        default={},
        hint='dict',
        order=3
        )
      }}"
    _maria_cfg_mariadb_binlog: "{{ {} | r_pufky.data.v3(
        section='50-mariadb-clients.cnf',
        key='maria_cfg_mariadb_binlog',
        raw=maria_cfg_mariadb_binlog,
        default={},
        hint='dict',
        order=4
        )
      }}"
    _maria_cfg_mariadb_check: "{{ {} | r_pufky.data.v3(
        section='50-mariadb-clients.cnf',
        key='maria_cfg_mariadb_check',
        raw=maria_cfg_mariadb_check,
        default={},
        hint='dict',
        order=5
        )
      }}"
    _maria_cfg_mariadb_dump: "{{ {} | r_pufky.data.v3(
        section='50-mariadb-clients.cnf',
        key='maria_cfg_mariadb_dump',
        raw=maria_cfg_mariadb_dump,
        default={},
        hint='dict',
        order=6
        )
      }}"
    _maria_cfg_mariadb_import: "{{ {} | r_pufky.data.v3(
        section='50-mariadb-clients.cnf',
        key='maria_cfg_mariadb_import',
        raw=maria_cfg_mariadb_import,
        default={},
        hint='dict',
        order=7
        )
      }}"
    _maria_cfg_mariadb_show: "{{ {} | r_pufky.data.v3(
        section='50-mariadb-clients.cnf',
        key='maria_cfg_mariadb_show',
        raw=maria_cfg_mariadb_show,
        default={},
        hint='dict',
        order=8
        )
      }}"
    _maria_cfg_mariadb_slap: "{{ {} | r_pufky.data.v3(
        section='50-mariadb-clients.cnf',
        key='maria_cfg_mariadb_slap',
        raw=maria_cfg_mariadb_slap,
        default={},
        hint='dict',
        order=9
        )
      }}"
    _maria_cfg_mariadb_client_server: "{{ {} | r_pufky.data.v3(
        section='50-mariadb.cnf',
        key='maria_cfg_mariadb_client_server',
        raw=maria_cfg_mariadb_client_server,
        default={'socket': '/run/mysqld/mysqld.sock'},
        hint='dict',
        order=1
        )
      }}"
    _maria_cfg_mariadb_include_confd_enable: "{{ {} | r_pufky.data.v3(
        section='50-mariadb.cnf',
        key='maria_cfg_mariadb_include_confd_enable',
        raw=maria_cfg_mariadb_include_confd_enable,
        default=true,
        _include='!includedir /etc/mysql/conf.d/',
        hint='bool',
        order=2
        )
      }}"
    _maria_cfg_mariadb_include_mariadb_confd_enable: "{{ {} | r_pufky.data.v3(
        section='50-mariadb.cnf',
        key='maria_cfg_mariadb_include_mariadb_confd_enable',
        raw=maria_cfg_mariadb_include_mariadb_confd_enable,
        default=true,
        _include='!includedir ' ~ maria_role_confd ~ '/',
        hint='bool',
        order=3
        )
      }}"
    _maria_cfg_server_server: "{{ {} | r_pufky.data.v3(
        section='50-server.cnf',
        key='maria_cfg_server_server',
        raw=maria_cfg_server_server,
        default={},
        _dest=maria_role_confd ~ '/50-server.cnf',
        hint='dict',
        order=1
        )
      }}"
    _maria_cfg_server_mariadb: "{{ {} | r_pufky.data.v3(
        section='50-server.cnf',
        key='maria_cfg_server_mariadb',
        raw=maria_cfg_server_mariadb,
        default=[{'version': 'all',
                  'config': {
                    'pid_file': '/run/mysqld/mysqld.pid',
                    'basedir': '/usr',
                    'bind_address': '127.0.0.1',
                    'expire_logs_days': 10,
                 }}],
        _versioned_configs=[],
        hint='list of dict',
        order=2
        )
      }}"
    _maria_cfg_server_embedded: "{{ {} | r_pufky.data.v3(
        section='50-server.cnf',
        key='maria_cfg_server_embedded',
        raw=maria_cfg_server_embedded,
        default={},
        hint='dict',
        order=3
        )
      }}"
    _maria_cfg_databases: "{{ {} | r_pufky.data.v3(
        section='databases',
        raw=maria_cfg_databases,
        default=[],
        hint='list of dict',
        sensitive=true,
        order=9
        )
      }}"
    _maria_cfg_databases_backup_enable: "{{ {} | r_pufky.data.v3(
        section='databases',
        raw=maria_cfg_databases_backup_enable,
        default=true,
        hint='bool',
        order=10
        )
      }}"
    _maria_cfg_databases_backup_all_enable: "{{ {} | r_pufky.data.v3(
        section='databases',
        raw=maria_cfg_databases_backup_all_enable,
        default=true,
        hint='bool',
        order=11
        )
      }}"
    _maria_cfg_databases_backup_individual_enable: "{{ {} | r_pufky.data.v3(
        section='databases',
        raw=maria_cfg_databases_backup_individual_enable,
        default=true,
        hint='bool',
        order=12
        )
      }}"
    _maria_cfg_databases_backup_dir: "{{ {} | r_pufky.data.v3(
        section='databases',
        raw=maria_cfg_databases_backup_dir | regex_replace('\\/$', ''),
        default='/var/lib/maria_backup',
        _dest=maria_role_confd ~ '/maria_backup',
        hint='str',
        order=13
        )
      }}"
    _maria_cfg_databases_backup_owner: "{{ {} | r_pufky.data.v3(
        section='databases',
        raw=maria_cfg_databases_backup_owner,
        default='root',
        hint='str',
        order=14
        )
      }}"
    _maria_cfg_databases_backup_group: "{{ {} | r_pufky.data.v3(
        section='databases',
        raw=maria_cfg_databases_backup_group,
        default='root',
        hint='str',
        order=15
        )
      }}"
    _maria_cfg_databases_backup_schedule: "{{ {} | r_pufky.data.v3(
        section='databases',
        raw=maria_cfg_databases_backup_schedule,
        default='weekly',
        hint='str',
        order=16
        )
      }}"
    _maria_cfg_databases_backup_options: "{{ {} | r_pufky.data.v3(
        section='databases',
        raw=maria_cfg_databases_backup_options,
        default=['--routines', '--events', '--triggers', '--complete-insert',
                '--create-options', '--single-transaction'],
        _options=maria_cfg_databases_backup_options | join(' '),
        hint='list of str',
        sensitive=true,
        order=9
        )
      }}"
    _maria_cfg_users: "{{ {} | r_pufky.data.v3(
        section='users',
        raw=maria_cfg_users,
        default=[],
        hint='list of dict',
        sensitive=true,
        order=1
        )
      }}"

- name: 'Annotate | generate version specific configs'
  ansible.builtin.set_fact:
    _maria_cfg_server_mariadb: '{{
        _maria_cfg_server_mariadb |
        combine({"_versioned_configs":
                 _maria_cfg_server_mariadb._versioned_configs |
                 default([]) + [item.config | default({})]})
      }}'
  loop: '{{ _maria_cfg_server_mariadb.raw }}'
  loop_control:
    label: '{{ item.version }}'

- name: 'Annotate | generate config sections'
  ansible.builtin.set_fact:
    _maria:
      dbs: '{{
          ([_maria_cfg_mariadb_client_server.raw.datadir | default("")] +
           [_maria_cfg_server_server.raw.datadir | default("")] +
            _maria_cfg_server_mariadb._versioned_configs +
           [_maria_server_embedded.raw.datadir | default("")]) |
               flatten | unique | reject("equalto", "")
        }}'
