---
###############################################################################
# MariaDB Config
###############################################################################
# Deploy configuration files to standard directory and secured files to a
# separately restricted directory with restricted file permissions.

- name: '{{ "Config | filesystem | set " ~ maria__srv._cfg }}'
  when: maria__srv._cfg | length > 0
  ansible.builtin.template:
    src: '{{ maria__srv._cfg }}'
    dest: '{{ maria___app._cfg }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Config | filesystem | deploy " ~ maria___app._conf_d }}'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ maria___app._conf_d }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: '{{ query("community.general.filetree", maria__srv._conf_d) }}'
  loop_control:
    label: '{{ item.path }}'
  when: item.state == 'file'
  register: maria__local

- name: 'Config | filesystem | query remote files'
  ansible.builtin.find:
    paths: '{{ maria___app._conf_d }}'
    file_type: 'file'
    recurse: true
  register: maria__remote

- name: 'Config | filesystem | remove unmanaged files'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ maria__remote.files }}'
  loop_control:
    label: '{{ item.path }}'
  when: >
    item.path not in maria__local.results | selectattr('dest', 'defined') |
    map(attribute='dest') | list

- name: '{{ "Config | filesystem | deploy " ~ maria___app._secure_conf_d }}'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ maria___app._secure_conf_d }}'
    owner: 'root'
    group: 'root'
    mode: '0640'
  loop: '{{ query("community.general.filetree", maria__srv._secure_conf_d) }}'
  loop_control:
    label: '{{ item.path }}'
  when: item.state == 'file'
  register: maria__local

- name: 'Config | filesystem | query remote files'
  ansible.builtin.find:
    paths: '{{ maria___app._secure_conf_d }}'
    file_type: 'file'
    recurse: true
  register: maria__remote

- name: 'Config | filesystem | remove unmanaged files'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ maria__remote.files }}'
  loop_control:
    label: '{{ item.path }}'
  when: >
    item.path not in maria__local.results | selectattr('dest', 'defined') |
    map(attribute='dest') | list
