---
###############################################################################
# MariaDB Config
###############################################################################
# Deploy configuration files to standard directory and secured files to a
# separately restricted directory with restricted file permissions.

- name: '{{ "Config | filesystem | set " ~ maria__srv._cfg }}'
  when: maria__srv._cfg | length > 0
  ansible.builtin.template:
    src: '{{ maria__srv._cfg }}'
    dest: '{{ maria___app._cfg }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Config | filesystem | set " ~ maria___app._conf_d }}'
  when: maria__srv._conf_d | length > 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ maria___app._conf_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'
      loop: '{{ query("community.general.filetree", maria__srv._conf_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ maria___app._conf_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0644'
      loop: '{{ query("community.general.filetree", maria__srv._conf_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ maria___app._conf_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: maria__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ maria__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", maria__srv._conf_d) |
          map(attribute='path') |
          map('regex_replace', '^', maria___app._conf_d ~ "/") | list
        )

- name: '{{ "Config | filesystem | query " ~ maria___app._conf_d }}'
  when: maria__srv._conf_d | length == 0
  ansible.builtin.find:
    paths: "{{ maria___app._conf_d }}"
    recurse: false  # Don't need to enumerate sub-directories to remove.
    hidden: true
  register: maria__cmd

- name: '{{ "Config | filesystem | clear " ~ maria___app._conf_d }}'
  when: maria__srv._conf_d | length == 0
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ maria__cmd.files }}"

- name: '{{ "Config | filesystem | set " ~ maria___app._secure_conf_d }}'
  when: maria__srv._secure_conf_d | length > 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ maria___app._secure_conf_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0750'
        state: 'directory'
      loop:
        '{{ query("community.general.filetree", maria__srv._secure_conf_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ maria___app._secure_conf_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0640'
      loop:
        '{{ query("community.general.filetree", maria__srv._secure_conf_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ maria___app._secure_conf_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: maria__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ maria__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", maria__srv._secure_conf_d) |
          map(attribute='path') |
          map('regex_replace', '^', maria___app._secure_conf_d ~ "/") | list
        )

- name: '{{ "Config | filesystem | query " ~ maria___app._secure_conf_d }}'
  when: maria__srv._secure_conf_d | length == 0
  ansible.builtin.find:
    paths: "{{ maria___app._secure_conf_d }}"
    recurse: false  # Don't need to enumerate sub-directories to remove.
    hidden: true
  register: maria__cmd

- name: '{{ "Config | filesystem | clear " ~ maria___app._secure_conf_d }}'
  when: maria__srv._secure_conf_d | length == 0
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ maria__cmd.files }}"
