---
###############################################################################
# MariaDB Install
###############################################################################
# Install required packages for utilities and MariaDB. Stop service to apply
# service changes (service must have new settings loaded to apply security,
# user, and database changes).
#
# Reference:
# * https://downloads.mariadb.org/mariadb/repositories/
# * https://mariadb.com/docs/features/mariadb-enterprise-server/
# * https://computingforgeeks.com/how-to-install-mariadb-on-debian/
# * https://github.com/geerlingguy/ansible-role-mysql

- name: 'Install | filesystem | set service directories'
  ansible.builtin.file:
    path: '{{ maria___app._secure_conf_d }}'
    owner: 'root'
    group: 'root'
    mode: '0750'
    state: 'directory'

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ maria___packages }}'
    apt_sources: '{{ maria___apt_sources }}'
    apt_srv_package_update_cache: true

- name: 'Install | systemd | stop mariadb.service'
  ansible.builtin.systemd:
    name: 'mariadb.service'
    state: 'stopped'
  failed_when: false

- name: '{{ "Install | filesystem | set minimal " ~ maria___app._cfg }}'
  when: maria__srv._cfg | length == 0
  ansible.builtin.template:
    src: 'templates/default/mariadb.cnf'
    dest: '{{ maria___app._cfg }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{  "Install | filesystem | set minimal " ~ maria___app._conf_d }}'
  when: maria__srv._conf_d | length == 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ maria___app._conf_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'
      loop: '{{
          query("community.general.filetree",
                "templates/default/mariadb.conf.d")
        }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ maria___app._conf_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0644'
      loop: '{{
          query("community.general.filetree",
                "templates/default/mariadb.conf.d")
        }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ maria___app._conf_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: maria__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ maria__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree",
                "templates/default/mariadb.conf.d") |
          map(attribute='path') |
          map('regex_replace', '^', maria___app._conf_d ~ "/") | list
        )
