---
###############################################################################
# MariaDB Install
###############################################################################
# Install required packages for utilities and MariaDB. Stop service to apply
# service changes (service must have new settings loaded to apply security,
# user, and database changes).
#
# Reference:
# * https://downloads.mariadb.org/mariadb/repositories/
# * https://mariadb.com/docs/features/mariadb-enterprise-server/
# * https://computingforgeeks.com/how-to-install-mariadb-on-debian/
# * https://github.com/geerlingguy/ansible-role-mysql

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ maria_role_packages }}'
    apt_sources: '{{ maria_role_apt_sources }}'
    apt_package_update_cache: true

- name: 'Install | stop services'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'stopped'
  failed_when: false
  loop:
    - 'mariadb.service'
