---
###############################################################################
# MariaDB Install
###############################################################################
# Add role user, install required packages for utilities and MariaDB. Stop
# service to apply service changes (service must have new settings loaded to
# apply security, user, and database changes).
#
# Reference:
# * https://downloads.mariadb.org/mariadb/repositories/
# * https://mariadb.com/docs/features/mariadb-enterprise-server/
# * https://computingforgeeks.com/how-to-install-mariadb-on-debian/
# * https://github.com/geerlingguy/ansible-role-mysql

- name: 'Install | manage users'
  when: maria_create_user
  ansible.builtin.include_role:
    name: 'r_pufky.srv.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_group: '{{ maria_role_group }}'
    users_role_user: '{{ maria_role_user }}'

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.apt'
  vars:
    apt_packages:
      - '{{ maria_role_packages }}'
    apt_sources: '{{ maria_role_apt_sources }}'
    apt_package_update_cache: true

- name: 'Install | stop service'
  ansible.builtin.systemd:
    name: 'mariadb'
    state: 'stopped'
