---
###############################################################################
# MariaDB Import DB
###############################################################################
# If the database is newly created, automatically attempt to import the latest
# backup.
#
# Imports using maria_flg_backup generate archives with a single file in it;
# otherwise copy a single text .sql file from the controller and execute
# import. If the import fails, cleanup the staged database.
#
# Args:
#   db: dict - maria_cfg_dbs database definition.
#
# Reference:
# * https://semisignal.com/mysql-database-import-with-ansible/

- name: 'Manage DB | fact | parse import options'
  ansible.builtin.set_fact:
    maria__import_db: "{{ {} | r_pufky.data.v3(

        _enable=db.extensions.db_import.enable | default(false),
        _source=db.extensions.db_import.source | default(''),
      ) }}"

# When state=present, this will only ever create a database if it does not
# exist (changed results) otherwise database will not be changed; safe to
# trigger import on change.
- name: '{{ "Manage DB | SQL | set " ~ db.name }}'
  community.mysql.mysql_db:
    ca_cert: '{{ db.ca_cert | default(omit) }}'
    chdir: '{{ db.chdir | default(omit) }}'
    check_hostname: '{{ db.check_hostname | default(omit) }}'
    check_implicit_admin: '{{ db.check_implicit_admin | default(false) }}'
    client_cert: '{{ db.client_cert | default(omit) }}'
    client_key: '{{ db.client_key | default(omit) }}'
    collation: '{{ db.collation | default("utf8_unicode_520_ci") }}'
    config_file: '{{ db.config_file | default("~/.my.cnf") }}'
    config_overrides_defaults:
      '{{ db.config_overrides_defaults | default(false) }}'
    connect_timeout: '{{ db.connect_timeout | default(30) }}'
    dump_extra_args: '{{ db.dump_extra_args | default(omit) }}'
    encoding: '{{ db.encoding | default("utf8") }}'
    force: '{{ db.force | default(false) }}'
    hex_blob: '{{ db.hex_blob | default(false) }}'
    ignore_tables: '{{ db.ignore_tables | default(omit) }}'
    login_host: '{{ db.login_host | default("localhost") }}'
    login_password: '{{ db.login_password | default(omit) }}'
    login_port: '{{ db.login_port | default(3306) }}'
    login_unix_socket:
      '{{ db.login_unix_socket | default(maria___app._socket) }}'
    login_user: '{{ db.login_user | default(omit) }}'
    master_data: '{{ db.master_data | default(0) }}'
    name: '{{ db.name }}'
    pipefail: '{{ db.pipefail | default(true) }}'
    quick: '{{ db.quick | default(true) }}'
    restrict_config_file: '{{ db.restrict_config_file | default(false) }}'
    single_transaction: '{{ db.single_transaction | default(false) }}'
    skip_lock_tables: '{{ db.skip_lock_tables | default(false) }}'
    sql_log_bin: '{{ db.sql_log_bin | default(true) }}'
    state: '{{ db.state | default("present") }}'
    target: '{{ db.target | default(omit) }}'
    unsafe_login_password: '{{ db.unsafe_login_password | default(false) }}'
    use_shell: '{{ db.use_shell | default(false) }}'
  register: maria__cmd

- name: 'Manage DB | import'
  when: maria__import_db._enable and maria__cmd.changed
  block:
    - name: '{{ "Manage DB | filesystem | stage " ~ maria__import_db._source }}'
      when: maria__import_db._source | length > 0
      ansible.builtin.copy:
        src: '{{ maria__import_db._source }}'
        dest: '{{ maria___app._stage }}'
        owner: 'root'
        group: 'root'
        mode: '0600'
        force: true

    - name: '{{
          "Manage DB | filesystem | stage " ~ maria__cfg._backup_d ~ "/" ~
          db.name ~ "-latest.sql"
        }}'
      when: maria__import_db._source | length == 0
      ansible.builtin.copy:
        src: '{{ maria__cfg._backup_d ~ "/" ~ db.name ~ "-latest.sql" }}'
        dest: '{{ maria___app._stage }}'
        remote_src: true
        owner: 'root'
        group: 'root'
        mode: '0600'
        force: true

    - name: '{{ "Manage DB | SQL | import " ~ db.name }}'
      community.mysql.mysql_db:  # noqa no-handler import DB immediately.
        ca_cert: '{{ db.ca_cert | default(omit) }}'
        chdir: '{{ db.chdir | default(omit) }}'
        check_hostname: '{{ db.check_hostname | default(omit) }}'
        check_implicit_admin: '{{ db.check_implicit_admin | default(false) }}'
        client_cert: '{{ db.client_cert | default(omit) }}'
        client_key: '{{ db.client_key | default(omit) }}'
        collation: '{{ db.collation | default("utf8_unicode_520_ci") }}'
        config_file: '{{ db.config_file | default("~/.my.cnf") }}'
        config_overrides_defaults:
          '{{ db.config_overrides_defaults | default(false) }}'
        connect_timeout: '{{ db.connect_timeout | default(30) }}'
        dump_extra_args: '{{ db.dump_extra_args | default(omit) }}'
        encoding: '{{ db.encoding | default("utf8") }}'
        force: '{{ db.force | default(false) }}'
        hex_blob: '{{ db.hex_blob | default(false) }}'
        ignore_tables: '{{ db.ignore_tables | default(omit) }}'
        login_host: '{{ db.login_host | default("localhost") }}'
        login_password: '{{ db.login_password | default(omit) }}'
        login_port: '{{ db.login_port | default(3306) }}'
        login_unix_socket:
          '{{ db.login_unix_socket | default(maria___app._socket) }}'
        login_user: '{{ db.login_user | default(omit) }}'
        master_data: '{{ db.master_data | default(0) }}'
        name: '{{ db.name }}'
        pipefail: '{{ db.pipefail | default(true) }}'
        quick: '{{ db.quick | default(true) }}'
        restrict_config_file: '{{ db.restrict_config_file | default(false) }}'
        single_transaction: '{{ db.single_transaction | default(false) }}'
        skip_lock_tables: '{{ db.skip_lock_tables | default(false) }}'
        sql_log_bin: '{{ db.sql_log_bin | default(true) }}'
        state: 'import'
        target: '{{ maria___app._stage }}'
        unsafe_login_password:
          '{{ db.unsafe_login_password | default(false) }}'
        use_shell: '{{ db.use_shell | default(false) }}'
  always:
    - name: 'Manage DB | filesystem | remove staged files'
      ansible.builtin.file:
        path: '{{ maria___app._stage }}'
        state: 'absent'
