---
# yamllint disable rule:line-length
###############################################################################
# MariaDB Import DB
###############################################################################
# If the database is newly created, automatically attempt to import the latest
# backup.
#
# Imports using maria_databases_backup_enable generate archives with a single
# file in it; otherwise copy a single text .sql file from the controller and
# execute import. If the import fails, cleanup the staged database.
#
# Args:
#   db: dict - maria_databases database definition.
#
# Reference:
# * https://semisignal.com/mysql-database-import-with-ansible/

- name: 'Manage | DB | parse import options'
  ansible.builtin.set_fact:
    _maria_db_import_enable: '{{ db.extensions.db_import.enable | default(false) }}'
    _maria_db_import_source: '{{ db.extensions.db_import.source | default("") }}'

# When state=present, this will only ever create a database if it does not
# exist (changed results) otherwise database will not be changed; safe to
# trigger import on change.
- name: 'Manage | DB | set {{ db.name }}'
  community.mysql.mysql_db:
    ca_cert: '{{ db.ca_cert | default(omit) }}'
    chdir: '{{ db.chdir | default(omit) }}'
    check_hostname: '{{ db.check_hostname | default(omit) }}'
    check_implicit_admin: '{{ db.check_implicit_admin | default(false) }}'
    client_cert: '{{ db.client_cert | default(omit) }}'
    client_key: '{{ db.client_key | default(omit) }}'
    collation: '{{ db.collation | default("utf8_unicode_520_ci") }}'
    config_file: '{{ db.config_file | default("~/.my.cnf") }}'
    config_overrides_defaults: '{{ db.config_overrides_defaults | default(false) }}'
    connect_timeout: '{{ db.connect_timeout | default(30) }}'
    dump_extra_args: '{{ db.dump_extra_args | default(omit) }}'
    encoding: '{{ db.encoding | default("utf8") }}'
    force: '{{ db.force | default(false) }}'
    hex_blob: '{{ db.hex_blob | default(false) }}'
    ignore_tables: '{{ db.ignore_tables | default(omit) }}'
    login_host: '{{ db.login_host | default("localhost") }}'
    login_password: '{{ db.login_password | default(omit) }}'
    login_port: '{{ db.login_port | default(3306) }}'
    login_unix_socket: '{{ db.login_unix_socket | default(maria_role_socket) }}'
    login_user: '{{ db.login_user | default(omit) }}'
    master_data: '{{ db.master_data | default(0) }}'
    name: '{{ db.name }}'
    pipefail: '{{ db.pipefail | default(true) }}'
    quick: '{{ db.quick | default(true) }}'
    restrict_config_file: '{{ db.restrict_config_file | default(false) }}'
    single_transaction: '{{ db.single_transaction | default(false) }}'
    skip_lock_tables: '{{ db.skip_lock_tables | default(false) }}'
    state: '{{ db.state | default("present") }}'
    target: '{{ db.target | default(omit) }}'
    unsafe_login_password: '{{ db.unsafe_login_password | default(false) }}'
    use_shell: '{{ db.use_shell | default(false) }}'
  register: _maria_db_created

- name: 'Manage | DB | import'
  when: _maria_db_import_enable and _maria_db_created.changed
  block:
    - name: 'Manage | DB | import | copy from controller'
      when: _maria_db_import_source | length > 0
      ansible.builtin.copy:
        src: '{{ _maria_db_import_source }}'
        dest: '/tmp/maria_db_import.sql'
        owner: 'root'
        group: 'root'
        mode: '0600'
        force: true

    - name: 'Manage | DB | import | copy from backups'
      when: _maria_db_import_source | length == 0
      ansible.builtin.copy:
        src: '{{ maria_databases_backup_dir }}/{{ db.name }}-latest.sql'
        dest: '/tmp/maria_db_import.sql'
        remote_src: true
        owner: 'root'
        group: 'root'
        mode: '0600'
        force: true

    - name: 'Manage | DB | import | {{ db.name }}'  # noqa no-handler import DB immediately.
      community.mysql.mysql_db:
        ca_cert: '{{ db.ca_cert | default(omit) }}'
        chdir: '{{ db.chdir | default(omit) }}'
        check_hostname: '{{ db.check_hostname | default(omit) }}'
        check_implicit_admin: '{{ db.check_implicit_admin | default(false) }}'
        client_cert: '{{ db.client_cert | default(omit) }}'
        client_key: '{{ db.client_key | default(omit) }}'
        collation: '{{ db.collation | default("utf8_unicode_520_ci") }}'
        config_file: '{{ db.config_file | default("~/.my.cnf") }}'
        config_overrides_defaults: '{{ db.config_overrides_defaults | default(false) }}'
        connect_timeout: '{{ db.connect_timeout | default(30) }}'
        dump_extra_args: '{{ db.dump_extra_args | default(omit) }}'
        encoding: '{{ db.encoding | default("utf8") }}'
        force: '{{ db.force | default(false) }}'
        hex_blob: '{{ db.hex_blob | default(false) }}'
        ignore_tables: '{{ db.ignore_tables | default(omit) }}'
        login_host: '{{ db.login_host | default("localhost") }}'
        login_password: '{{ db.login_password | default(omit) }}'
        login_port: '{{ db.login_port | default(3306) }}'
        login_unix_socket: '{{ db.login_unix_socket | default(maria_role_socket) }}'
        login_user: '{{ db.login_user | default(omit) }}'
        master_data: '{{ db.master_data | default(0) }}'
        name: '{{ db.name }}'
        pipefail: '{{ db.pipefail | default(true) }}'
        quick: '{{ db.quick | default(true) }}'
        restrict_config_file: '{{ db.restrict_config_file | default(false) }}'
        single_transaction: '{{ db.single_transaction | default(false) }}'
        skip_lock_tables: '{{ db.skip_lock_tables | default(false) }}'
        state: 'import'
        target: '/tmp/maria_db_import.sql'
        unsafe_login_password: '{{ db.unsafe_login_password | default(false) }}'
        use_shell: '{{ db.use_shell | default(false) }}'
  always:
    - name: 'Manage | DB | import | remove staged files'
      ansible.builtin.file:
        path: '/tmp/maria_db_import.sql'
        state: 'absent'
