---
###############################################################################
# Maria Prep
###############################################################################
# Set debconf data deletion policy, create user if needed and determine UID/GID
# for potential remote filesystems.

- name: 'Prep | set debconf postrm_remove_databases'
  ansible.builtin.debconf:
    name: 'mariadb-server'
    question: '{{ _maria_srv_purge_enable._question }}'
    vtype: 'boolean'
    value: '{{ _maria_srv_purge_enable._value }}'

- name: 'Prep | manage users'
  when: _maria_srv_create_user.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_user: '{{ maria_role_user }}'
    users_role_group: '{{ maria_role_group }}'

- name: 'Prep | enumerate system user {{ _maria_srv_user.raw }}'
  ansible.builtin.user:
    name: '{{ _maria_srv_user.raw }}'
  check_mode: true
  changed_when: false
  register: _maria_srv_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _maria_srv_user: '{{
        _maria_srv_user |
        combine({"_uid": _maria_srv_user_query.uid})
      }}'
    _maria_srv_group: '{{
        _maria_srv_group |
        combine({"_gid": _maria_srv_user_query.group})
      }}'
