---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.srv.maria'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.maria'

- name: 'Converge | disable auto-backup'
  hosts: 'maria-debian-13-auto_backup-disable'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.srv.maria'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.maria'
      vars:
        maria_cfg_databases_backup_enable: false
