---
# yamllint disable rule:line-length
###############################################################################
# Feature Flags
###############################################################################

# 1. Install application?
#
# Creates required default directories, users, install packages, download
# software, autogenerates config.xml if not specified, update and start
# services.
#
# Default: True.
maria_flg_install: true

# 2. Set configuration data?
#
# Overwrite config data directory sourced from maria_srv_cfg_d and app.ini from
# maria_srv_cfg. Stops service, deploys user config data, updates and starts
# services.
#
# Default: False.
maria_flg_config: false

# 3. Enable scheduled server backup?
#
# See maria_cfg_backup_*.
#
# Default: False
maria_flg_backup: false

###############################################################################
# Service
###############################################################################
# MariaDB is managed through root via unix socket connections. Root connection
# information is written to /root/.my.cnf.

# MariaDB Release.
#
# All versions are supported by the Maria Debian repository but may not be
# fully supported by the role.
#
# Versions (Schematic):
#       MAJOR: Unsafe - only major rolling release version is supported; older
#              versions may be used at the risk of missing dependencies or
#              configuration parameters that are not supported.
#       MINOR: Safe - Usually requires no role updates.
#       PATCH: Safe - Usually requires no role updates.
#   RECOMMEND: Only use latest rolling release.
#
# Default: '12.2'.
maria_srv_version: '12.2'

# MariaDB local root password.
#
# Role uses this account to manage MariaDB via local socket. Locked down in
# /root/.my.cnf.
#
# Password is automatically set and updated on role application for:
# * root@localhost
# * root@127.0.0.1
# * root@::1
#
# Generated password is predictable and should ALWAYS be changed.
#
# Default: '{RANDOM}' (idempotent based on hostname).
maria_srv_password: '{{
    lookup("ansible.builtin.password",
           "/dev/null",
           chars=["ascii_lowercase", "ascii_uppercase", "digits"],
           length=32,
           seed=inventory_hostname)
  }}'

# Purge MariaDB data directories on package removal?
#
# DATA DESTRUCTIVE. Removes DB's, state, and config on Debian package removal.
# Prevents 'apt remove mariadb-server' from deleting data.
#
# Default: False (Debian default).
maria_srv_purge: false

# MariaDB mariadb.cnf to set.
#
# Ansible controller path to source mariadb.cnf (treated as a jinja2 template
# allowing for ansible variable interpretation). Overwrites existing
# /etc/mysql/mariadb.cnf.
#
# A default configuration is autogenerated if not provided (see
# templates/default).
#
# maria_srv_cfg: 'host_vars/maria.example.com/mariadb.cnf'
#
# Default: '' (use minimally configured default).
maria_srv_cfg: ''

# MariaDB conf.d to set.
#
# Ansible controller path to source conf.d files (treated as a jinja2 templates
# allowing for ansible variable interpretation). Overwrites existing config
# data in /etc/mysql/mariadb.conf.d/*. Files not sourced will be removed.
#
# Required default maria configuration is auto-generated if not set (see
# templates/default).
#
# maria_srv_conf_d: 'host_vars/maria.example.com/conf.d'
#
# Default: '' (use minimally configured default).
maria_srv_conf_d: ''

# MariaDB secure conf.d to set.
#
# Ansible controller path to source secure conf.d files (treated as a jinja2
# templates allowing for ansible variable interpretation). Overwrites existing
# config data in /etc/mysql/secure.conf.d/* with 0750:0640 maria_srv_user,
# maria_srv_group permissions. Certificates, etc. should be included here and
# sourced from standard conf.d and configuration files. Files not sourced will
# be removed.
#
# maria_srv_secure_conf_d: 'host_vars/maria.example.com/secure.conf.d'
#
# Default: '' (disabled).
maria_srv_secure_conf_d: ''

# User that MariaDB will run under.
#
# 'mysql' will automatically be created using vars/main.yml if required.
# All other accounts are checked for existence.
#
# Default: 'mysql'.
maria_srv_user: 'mysql'

# Group that MariaDB will run under.
#
# 'mysql' will automatically be created using vars/main.yml if required.
# All other accounts are checked for existence.
#
# Default: 'mysql'.
maria_srv_group: 'mysql'

###############################################################################
# Config
###############################################################################

# Databases to manage.
#
# Use community.mysql.mysql_db parameters as dictionary keys with default
# values matching specified parameters unless noted. Additional attributes are
# fully defined.
#
# maria_cfg_dbs:
#     list of dict - Encapsulated community.mysql.mysql_db dictionaries.
#   - collation: str - Collation mode (sorting). This only applies to new
#           table/databases and does not update existing ones, this is a
#           limitation of MySQL. Do not use utf8_general_ci going forward.
#         Default: 'utf8_unicode_520_ci' (UTF8, case insensitive).
#     encoding: str - Encoding mode to use at creation of database, dump or
#           importation of sql script.
#         Default: 'utf8'.
#     login_unix_socket: str - Unix domain socket path for local connections.
#         Special Case:
#           *: Use this parameter to avoid error:
#              'Please explicitly state intended protocol'.
#         Default: '/run/mysqld/mysqld.sock'.
#     extensions: dict - Database role extensions.
#       db_import: dict - Database import options.
#         enable: bool - Enable imports?
#               Import occurs only on database creation and is skipped for
#               existing databases.
#             Default: False.
#         source: str - database to import.
#               Source file is copied, imported, then removed.
#             Values:
#               {PATH}: Sourced from ansible controller; must NOT be compressed
#                       archive.
#
#                       source: 'host_vars/db.example.com/data/skeleton.sql'
#                   '': Use 'latest' individual DB backup from
#                       maria_cfg_dbs_backup_dir (default).
#             Default: '' (use latest backup).
#
# maria_cfg_dbs:
#   - name: 'example_import_from_controller'
#     collation: 'utf8_unicode_520_ci'
#     encoding: 'utf8'
#     state: 'present'
#     extensions:
#       db_import:
#         enable: true
#         source: 'host_vars/db.example.com/data/skeleton_db.sql'
#   - name: 'example_import_from_latest_backup'
#     collation: 'utf8_unicode_520_ci'
#     encoding: 'utf8'
#     state: 'present'
#     extensions:
#       db_import:
#         enable: true
#
# Default: [].
#
# Reference:
# * https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_db_module.html
# * https://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
maria_cfg_dbs: []

# Database users to manage.
#
# Use community.mysql.mysql_user parameters as dictionary keys with default
# values matching specified parameters unless noted. Users are managed via
# MariaDB local root account.
#
# maria_cfg_users:
#     list of dict - Encapsulated community.mysql.mysql_user dictionaries.
#   - login_unix_socket: str - Unix domain socket path for local connections.
#         Special Case:
#           *: Use this parameter to avoid error:
#              'Please explicitly state intended protocol'.
#         Default: '/run/mysqld/mysqld.sock'.
#
# maria_cfg_users:
#   - name: 'example'
#     host 'localhost'
#     password: '{{ vault_password }}'
#     priv: '*.*:USAGE'
#     state: 'present'
#     append_privs: false
#     encrypted: false
#
# Default: [].
#
# Reference:
# * https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_user_module.html
maria_cfg_users: []

# Backup
###############################################################################
# Backups are done through mariadb-dump and executed as root on a
# schedule, Databases date stamped, linked to 'latest', removing 'other'
# permissions.
#
# Systems with remote mount points restricting writes from local root user will
# fail.
#
# All backups except 'latest' are compressed with tar.xz.
#
# Disable if custom or complex backups are needed.

# Enable all database backups?
#
# May be used with maria_cfg_dbs_backup_individual_enable.
#
# All databases will be backed up to:
# * maria_cfg_dbs_backup_dir/all-databases-{DATE}.sql
# * maria_cfg_dbs_backup_dir/all-databases-latest.sql ->
#   maria_cfg_dbs_backup_dir/all-databases-{DATE}.sql
#
# Default: True.
maria_cfg_backup_all: true

# Enable individual database backups?
#
# May be used with maria_cfg_dbs_backup_all.
#
# All databases will be backed up individually to:
# * maria_cfg_dbs_backup_dir/{DB}-{DATE}.sql
# * maria_cfg_dbs_backup_dir/{DB}-latest.sql ->
#   maria_cfg_dbs_backup_dir/{DB}-{DATE}.sql
#
# Default: True.
maria_cfg_backup_individual: true

# Backup location.
#
# Directory will be created with root permissions.
#
# Default: '/srv/maria_backup'.
maria_cfg_backup_d: '/srv/maria_backup'

# Backup file owner. Default: 'root'.
maria_cfg_backup_owner: 'root'

# Backup file group. Default: 'root'.
maria_cfg_backup_group: 'root'

# Set backup schedule.
#
# Uses systemd TIME specification.
#
# Default: 'weekly'
#
# Reference:
# * https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html
maria_cfg_backup_schedule: 'weekly'

# List of mariadb-dump options for backing up databases.
#
# All options (user/password or auth file) must be specified.
#
# Default:
#   - '--defaults-file=/root/.my.cnf'
#   - '--routines'
#   - '--events'
#   - '--triggers'
#   - '--complete-insert'
#   - '--create-options'
#   - '--single-transaction'
#
# Reference:
# * https://manpages.debian.org/trixie/mariadb-client/mariadb-dump.1.en.html
maria_cfg_backup_opts:
  - '--defaults-file=/root/.my.cnf'
  - '--routines'
  - '--events'
  - '--triggers'
  - '--complete-insert'
  - '--create-options'
  - '--single-transaction'
