---
- name: 'Verify | database'
  hosts: 'all'
  gather_facts: false
  tasks:
    # Service will not start if minimal configs are wrong.
    - name: 'Verify | SQL | query test1 user'
      community.mysql.mysql_query:
        login_db: 'mysql'
        query: 'SELECT user FROM mysql.user WHERE user="test1" and host="%"'
        login_unix_socket: '/run/mysqld/mysqld.sock'
      register: maria__test_query

    - name: 'Verify | assert | test1 user created'
      ansible.builtin.assert:
        quiet: true
        that: maria__test_query.rowcount[0] == 1
        fail_msg: ✘ test1@% should have been created.

    - name: 'Verify | SQL | query test2 user'
      community.mysql.mysql_query:
        login_db: 'mysql'
        query: 'SELECT user FROM mysql.user WHERE user="test2" and host="%"'
        login_unix_socket: '/run/mysqld/mysqld.sock'
      register: maria__test_query

    - name: 'Verify | assert | test2 user created'
      ansible.builtin.assert:
        quiet: true
        that: maria__test_query.rowcount[0] == 1
        fail_msg: ✘ test2@% should have been created.

    - name: 'Verify | SQL | query skeleton database'
      community.mysql.mysql_query:
        login_db: 'mysql'
        query: 'SELECT schema_name FROM information_schema.schemata WHERE schema_name="skeleton"'  # yamllint disable-line rule:line-length
        login_unix_socket: '/run/mysqld/mysqld.sock'
      register: maria__test_query

    - name: 'Verify | assert | skeleton database created'
      ansible.builtin.assert:
        quiet: true
        that: maria__test_query.rowcount[0] == 1
        fail_msg: ✘ skeleton database should have been created.

    - name: 'Verify | SQL | query skeleton.default table'
      community.mysql.mysql_query:
        login_db: 'mysql'
        query: 'SELECT * FROM information_schema.tables WHERE table_schema="skeleton" AND table_name="default"'  # yamllint disable-line rule:line-length
        login_unix_socket: '/run/mysqld/mysqld.sock'
      register: maria__test_query

    - name: 'Verify | assert | skeleton.default exists'
      ansible.builtin.assert:
        quiet: true
        that: maria__test_query.rowcount[0] == 1
        fail_msg: |

          ✘ skeleton.default table should exist.

          skeleton.modified should not have been imported.

    - name: 'Verify | SQL | query empty database'
      community.mysql.mysql_query:
        login_db: 'mysql'
        query: 'SELECT schema_name FROM information_schema.schemata WHERE schema_name="empty"'  # yamllint disable-line rule:line-length
        login_unix_socket: '/run/mysqld/mysqld.sock'
      register: maria__test_query

    - name: 'Verify | assert | empty database create'
      ansible.builtin.assert:
        quiet: true
        that: maria__test_query.rowcount[0] == 1
        fail_msg: ✘ empty database should have been created.

- name: 'Verify | config'
  hosts: 'all'
  gather_facts: false
  tasks:
    # Test configured conf_d, secure_conf_d, cfg options.
    - name: 'Verify | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: '{{ "Verify | test | " ~ maria___app._cfg }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ maria___app._cfg }}'
        test_src: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~ "/files/mariadb.cnf"
          }}'
        test_file: '{{ maria___app._cfg }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    - name: '{{ "Verify | test | " ~ maria___app._conf_d ~ "/50-server.cnf" }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          '{{ "Verify | test | " ~ maria___app._conf_d ~ "/50-server.cnf" }}'
        test_src: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/conf.d/50-server.cnf"
          }}'
        test_file: '{{ maria___app._conf_d ~ "/50-server.cnf" }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    - name: '{{
          "Verify | test | absent " ~ maria___app._conf_d ~ "/60-galera.cnf"
        }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'file.yml'
      vars:
        test_name: '{{
            "Verify | test | absent " ~ maria___app._conf_d ~ "/60-galera.cnf"
          }}'
        test_file: '{{ maria___app._conf_d ~ "/60-galera.cnf" }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_state: 'absent'
        test_diff: true

    - name: 'Verify | filesystem | query /srv/maria_backup'
      ansible.builtin.find:
        path: '/srv/maria_backup'
        patterns: '*.sql'
        file_type: 'file'
        recurse: false
      register: maria__backup

    - name: 'Verify | assert | backup triggered'
      ansible.builtin.assert:
        quiet: true
        that: 'maria__backup.matched >= 1'
        fail_msg: '✘ SQL backups should be triggered.'
