---
# yamllint disable rule:line-length
###############################################################################
# MariaDB Encryption
###############################################################################
# Encryption requires additional settings on each database and the generation
# of keys to use.
#
# Generate encryption keys with:
#
#   echo -n "1;`openssl rand -hex 32`" > keyfile
#   openssl rand -hex 128 > keyfile.key
#   openssl enc -aes-256-cbc -md sha1 -pass file:keyfile.key -in keyfile -out keyfile.enc
#
# Enable Encryption:
#   maria_encryption_enable: true
#   maria_encryption_path: 'host_vars/db.example.com/data/encryption'
#   maria_server_mariadb:
#     - version: 'all'
#       config:
#         pid_file: '/run/mysqld/mysqld.pid'
#         basedir: '/usr'
#         bind_address: '127.0.0.1'
#         expire_logs_days: 10
#         file_key_management_filename: '/etc/mysql/mariadb.conf.d/encryption/keyfile.enc'
#         file_key_management_filekey: 'FILE:/etc/mysql/mariadb.conf.d/encryption/keyfile.key'
#         file_key_management_encryption_algorithm: 'AES_CTR'
#
# Reference:
# * https://mariadb.com/kb/en/file-key-management-encryption-plugin/

# Enable data at rest encryption?
#
# Default settings will be included from 99-enable-encryption.cnf.preset/*. and
# file_key_management plugin will automatically be added.
#
# Reference:
# * https://mariadb.com/kb/en/file-key-management-encryption-plugin/
maria_encryption_enable: false

# Path to encryption files.
#
# Sourced from ansible controller; automatically placed in
# {{ maria_role_confd }}/encryption/ with correct permissions. Be sure to set
# appropriate paths for MariaDB configuration settings.
#
# maria_encryption_path: 'host_vars/db.example.com/data/encryption'
#
# Default: '' (disabled).
maria_encryption_path: ''

# Custom encryption settings.
#
# Encryption settings defined here will override preset settings.
#
# maria_encryption_settings:
#   - 'aria-encrypt-tables'
#   - 'encrypt-binlog'
#   - 'encrypt-tmp-disk-tables'
#   - 'encrypt-tmp-files'
#   - 'loose-innodb-encrypt-log'
#   - 'loose-innodb-encrypt-tables'
#
# Default: [].
maria_encryption_settings: []
