---
###############################################################################
# MariaDB Extensions ({{ maria_role_confd }}/90-extensions.cnf)
###############################################################################
# Manually specify additional preferences that are not explicitly defined in
# this config. Use to add additional options from future MariaDB updates that
# are not currently in the role. If you are using this section, please submit a
# bug with the specific key that needs to be added to the config.
#
# Extensions have precedence over defaults; any setting that is also defined in
# defaults will be overwritten with the value defined here.
#
# Deprecated options may be specified here.
#
# https://github.com/r-pufky/ansible_maria/issues
#
# _maria_cfg_extensions:
#     list of dict - MariaDB setting extensions.
#   - section: str - Section heading.
#     config: dict - MariaDB daemon configuration section settings.
#       {KEY}: str - Value.
#
# _maria_cfg_extensions:
#   - section: 'mariadbd'
#     config:
#       bind_address: '127.0.0.1'
#
# [maridbd]
# bind_address=127.0.0.1
#
# Default: {}
_maria_cfg_extensions: {}
