---
###############################################################################
# MariaDB Server (/etc/mysql/mariadb.cnf) Configuration
###############################################################################
# See maria_srv_certs_path for managing certificates.

# [client-server] section.
#
# This group is read both by the client and the server use it for options that
# affect everything. Setting should be in config/*.yml sections.
#
# Special Case:
#   datadir: Directory will automatically be created and permissions set using
#            maria_srv_user. The data directory will ONLY be initialized if a
#            corresponding 'mysql' db does not exist (corrupt or incomplete
#            data directories will cause service to fail).
#
# maria_srv_client_server:
#     dict - MariaDB configuration section settings.
#   {KEY}: str - Value.
#
# maria_srv_client_server:
#   datadir: '/var/lib/mysql'
#   tmpdir: '/tmp'
#   lc_messages: 'en_US'
#   bind_address: '127.0.0.1'
#
# Default:
#   socket: '/run/mysqld/mysqld.sock'
maria_cfg_mariadb_client_server:
  socket: '/run/mysqld/mysqld.sock'

# Enable include dir /etc/mysql/conf.d?
#
# Included after [client-server] before mariadb.conf.d.
#
# Special Case:
#   datadir: Manage directory manually.
#
# Default: True.
maria_cfg_mariadb_include_confd_enable: true

# Enable include dir maria_role_confd?
#
# Must be enabled to use any config/*.yml options. Included at end of file.
#
# Special Case:
#   datadir: Manage directory manually.
#
# Default: True.
maria_cfg_mariadb_include_mariadb_confd_enable: true
