---
###############################################################################
# MariaDB Server ({{ maria_role_confd }}/50-server.cnf)
###############################################################################
# See maria_srv_certs_path for managing certificates.

# [server] section.
#
# Read by standalone daemon and embedded servers.
#
# Special Case:
#   datadir: Directory will automatically be created and permissions set using
#            maria_srv_user. The data directory will ONLY be initialized if a
#            corresponding 'mysql' db does not exist (corrupt or incomplete
#            data directories will cause service to fail).
#
# maria_cfg_server_server:
#     dict - MariaDB server configuration section settings.
#   {KEY}: str - Value.
#
# maria_cfg_server_server:
#   datadir: '/var/lib/mysql'
#   tmpdir: '/tmp'
#   lc_messages: 'en_US'
#   bind_address: '127.0.0.1'
#
# Default: {}
#
# Reference:
# * https://mariadb.com/kb/en/server-system-variables/
maria_cfg_server_server: {}

# [mariadb*] sections.
#
# This group is only read by MariaDB servers running the specified versions.
#
# Special Case:
#   datadir: Directory will automatically be created and permissions set using
#            maria_srv_user. The data directory will ONLY be initialized if a
#            corresponding 'mysql' db does not exist (corrupt or incomplete
#            data directories will cause service to fail).
#
# maria_cfg_server_mariadb:
#     list of dict - MariaDB daemon configuration versioned section settings.
#   - version: str - MariaDB version settings apply to.
#         Special Case:
#           all: use [mariadbd] section header (applies all versions).
#     config: dict - MariaDB daemon configuration section settings.
#       {KEY}: str - Value.
#
# maria_cfg_server_mariadb:
#   - version: 'all'
#     config:
#       pid_file: 'run/mysqld/mysqld.pid'
#       basedir: 'usr'
#       bind_address: '127.0.0.1'
#       expire_logs_days: 10
#   - version: '11.7'
#     config:
#       datadir: '/var/lib/mysql-11.7'
#       bind_address: '192.168.0.1'
#
# [maridbd]
# pid_file=/run/mysqld/mysqld.pid
# basedir=/usr
# bind_address=127.0.0.1
# expire_logs_days=10
#
# [mariadb-11.7]
# datadir=/var/lib/mysql-11.7
# bind_address=192.168.0.1
#
# Default: {}
#
# Reference:
# * https://mariadb.com/kb/en/server-system-variables/
maria_cfg_server_mariadb:
  - version: 'all'
    config:
      pid_file: '/run/mysqld/mysqld.pid'
      basedir: '/usr'
      bind_address: '127.0.0.1'
      expire_logs_days: 10

# [embedded] section.
#
# Read by embedded server.
#
# Special Case:
#   datadir: Directory will automatically be created and permissions set using
#            maria_srv_user. The data directory will ONLY be initialized if a
#            corresponding 'mysql' db does not exist (corrupt or incomplete
#            data directories will cause service to fail).
#
# maria_cfg_server_embedded:
#     dict - MariaDB daemon configuration section settings.
#   {KEY}: str - Value.
#
# maria_cfg_server_embedded:
#   datadir: '/var/lib/mysql'
#   tmpdir: '/tmp'
#
# Default: {}
#
# Reference:
# * https://mariadb.com/kb/en/server-system-variables/
maria_cfg_server_embedded: {}
